################################################################################
# Yvan Vivid -- GTK3 settings
################################################################################

[Settings]
gtk-application-prefer-dark-theme=true
gtk-font-name=DejaVuSansMono Nerd Font 12
gtk-theme-name=Breeze-Dark
gtk-icon-theme-name=breeze-dark
gtk-fallback-icon-theme=gnome
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-menu-images=1
gtk-button-images=1
gtk-cursor-theme-name=breeze
gtk-cursor-theme-size=0
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintfull
gtk-xft-rgba=rgb
