################################################################################
# Yvan Vivid -- i3status bar config for i3status-rs
################################################################################

icons = "material-nf"

[theme]
name = "slick"
[theme.overrides]
idle_bg = "#700000"
idle_fg = "#00ff10"
info_bg = "#600000"
info_fg = "#10ff10"
good_bg = "#200050"
good_fg = "#ffa000"
warning_bg = "#002060"
warning_fg = "#f0ff10"
alternating_tint_fg = "#400000"
alternating_tint_bg = "#004050"

#[[block]]
#block = "custom"
#command = "bar-vivid-time"
#interval = 5

# cycle = -- cycle with regular time


[[block]]
block = "time"
interval = 60
format = "%a %F %R"

[[block]]
block = "cpu"
interval = 3
info = 40
warning = 65
critical = 90
format = "{utilization} {barchart}"

[[block]]
block = "memory"
display_type = "memory"
icons = true
clickable = true
interval = 5
critical_mem = 95
critical_swap = 80
format_mem = "{mem_free;M}({mem_total_used_percents})"

[[block]]
block = "load"
interval = 5
format = "{5m}/5s"

[[block]]
block = "net"
device = "wlp59s0"
interval = 5
format = " {ssid} {signal_strength}"

[[block]]
block = "sound"
driver = "auto"
step_width = 5
#on_click = "volume mute"

[[block]]
block = "backlight"

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
interval = 10
format = "{percentage} {percentage:6#100} ({time}) {power}W"
