################################################################################
# Yvan Vivid -- i3status bar config for i3status-rs
################################################################################
icons_format = "{icon}"

[theme]
theme = "slick"
[theme.overrides]
idle_bg = "#700000"
idle_fg = "#00ff10"
info_bg = "#600000"
info_fg = "#10ff10"
good_bg = "#200050"
good_fg = "#ffa000"
warning_bg = "#002060"
warning_fg = "#f0ff10"
alternating_tint_fg = "#400000"
alternating_tint_bg = "#004050"

[icons]
icons = "material-nf"

[[block]]
block = "custom"
command = "/usr/local/bin/vivid-time now --precision 2"
interval = 5

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%Y-%m-%d / %R') "
short = " $icon $timestamp.datetime(f:%R) "

[[block]]
block = "cpu"
format = " $icon $utilization $barchart "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "

[[block]]
block = "net"
format = " $icon  $ssid $signal_strength "
interval = 5

[[block]]
block = "temperature"
format = " $icon $average/$max "
interval = 10

[[block]]
block = "sound"
driver = "auto"
step_width = 5
#on_click = "volume mute"

[[block]]
block = "backlight"

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
interval = 10
format = " $icon $percentage - $time $power "
