#!/usr/bin/env bash

set -e

declare -r tpm_source="https://github.com/tmux-plugins/tpm"
declare -r tpm_plugins_path="$XDG_DATA_HOME/tmux/plugins"
declare -r tpm_path="$tpm_plugins_path/tpm"

pull_tpm() {
  git clone "$tpm_source" "$tpm_path"
}

install_tpm() {
  "$tpm_path/bin/install_plugins"
}

if [[ ! -e "$tpm_path" ]]; then
  echo "TPM not found. Bootstrapping TPM."
  mkdir -p "$tpm_plugins_path"
  pull_tpm
else
  echo "TPM found. Running install."
fi

install_tpm
