#!/usr/bin/env bash
# Yvan Vivid - Snapshot nix setup
source "$(dirname "${BASH_SOURCE[0]}")/lib.bash"

declare -r ts="$(date +%s)"
declare -r archname="etc-nixos-${ts}.tar.xz"
declare -r archpath="$target/$snaps/$archname"

log "Making archive snapshot [$archname]."
snapshot "$archpath"
log "Done making snapshot."
