#!/usr/bin/env bash
# Yvan Vivid - Update Nixos configuration
source "$(dirname "${BASH_SOURCE[0]}")/lib.bash"

assert_namefile

log "Updating nixos config"
rsyncr -ltr --filter="merge $filter" "$@" "$src/" "$target/"
log "Updated"
