# shellcheck shell=bash
echo "Loading bash settings."

# Common environment file
env="$HOME/.env"

# Try loading common variables
if [ -f "$env" ]; then
  # shellcheck disable=SC1090
  source "$env"
else
  echo "WARNING: no [$env]."
fi

# Export for sh and bash to pick when not login
export ENV="$env"
export BASH_ENV="$env"
